[package]
name = "ns-visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
rayon = "1.10.0"
regex = { version = "1.11.1", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
